### PR TITLE
Add keywords and example

### PR DESCRIPTION
**Pull request by CGastrell**
This PR adds

  - some keywords for discovery on the block search
  - the example to be shown on the block search
  - the block icon

The example demanded an extra attribute `isExample` so we could prevent the triggering of the autosaving function.

image

Suggestions are welcome.

## Test instructions
Checkout and `make client`. Use the block search with any of the keywords. See the example renders on mouse over.

### CODE REVIEW

**Comment by CGastrell** [comment]
The example needs to render a different block as it's creating a new NPS survey on every *hover*

**Review by ice9js — CHANGES_REQUESTED** [review]
Just one more nit: can we update the classes so `is-inactive` isn't applied when `isExample === true` ?

**Review by ice9js — APPROVED** [review]
:shipit:

**Comment by digitalwaveride** [comment]
Here some keyword suggestions:

net promoter score
nps
rating
feedback
customer satisfaction
review
survey
poll
form
Crowdsignal
loyalty
customer experience
CSAT

**Comment by digitalwaveride** [comment]
And here a first suggestion of the description:

`Measure your Net Promoter Score! Collect feedback and track customer satisfaction over time.`

**Comment by digitalwaveride** [comment]
Aaaannnd... and already an edit needed, sorry. 

I forgot that we need to adjust the title of the block slightly.

Title: 
`Measure NPS`

Description:
`Calculate your Net Promoter Score! Collect feedback and track customer satisfaction over time.`

image

**Review by digitalwaveride — APPROVED** [review]
YAY! 🚢  
Thanks Christian!

**Pull request merged**
